# Generated by Django 5.1.7 on 2025-03-24 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarStillMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('ambient_temperature', models.FloatField(help_text='Ambient temperature (°C)')),
                ('water_temperature', models.FloatField(help_text='Water temperature (°C)')),
                ('glass_temperature', models.FloatField(help_text='Glass temperature (°C)')),
                ('solar_radiation', models.FloatField(help_text='Solar radiation (W/m²)')),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed (m/s)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity (%)', null=True)),
                ('efficiency', models.FloatField(blank=True, help_text='Efficiency (%)', null=True)),
                ('freshwater_quantity', models.FloatField(blank=True, help_text='Fresh water produced (ml)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_file', models.FileField(upload_to='trained_models/')),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy (%)', null=True)),
                ('mse', models.FloatField(blank=True, help_text='Mean Squared Error', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this model is currently active for predictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_efficiency', models.FloatField(help_text='Predicted efficiency (%)')),
                ('predicted_freshwater', models.FloatField(help_text='Predicted fresh water quantity (ml)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.solarstillmeasurement')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='predictor.trainedmodel')),
            ],
        ),
    ]
